-- Persistent AI batch jobs for /dashboard/content-audit
-- AutoMigrate will create these tables on first use. Run manually only if you prefer controlled SQL migrations.

CREATE TABLE IF NOT EXISTS content_ai_jobs (
  id VARCHAR(80) NOT NULL,
  status VARCHAR(30) NOT NULL,
  mode VARCHAR(40) NOT NULL,
  model_strategy VARCHAR(40) NOT NULL,
  country_code VARCHAR(10) NOT NULL DEFAULT 'jo',
  content_type VARCHAR(30) NOT NULL,
  level VARCHAR(30) NOT NULL,
  query VARCHAR(500) NULL,
  `limit` BIGINT NOT NULL DEFAULT 50,
  concurrency BIGINT NOT NULL DEFAULT 2,
  total_items BIGINT NOT NULL DEFAULT 0,
  processed_items BIGINT NOT NULL DEFAULT 0,
  successful_items BIGINT NOT NULL DEFAULT 0,
  failed_items BIGINT NOT NULL DEFAULT 0,
  pending_items BIGINT NOT NULL DEFAULT 0,
  progress BIGINT NOT NULL DEFAULT 0,
  cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  error TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  INDEX idx_content_ai_jobs_status (status),
  INDEX idx_content_ai_jobs_country_code (country_code),
  INDEX idx_content_ai_jobs_created_at (created_at),
  INDEX idx_content_ai_jobs_finished_at (finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_ai_job_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id VARCHAR(80) NOT NULL,
  item_index BIGINT NOT NULL,
  content_type VARCHAR(30) NOT NULL,
  content_id BIGINT UNSIGNED NOT NULL,
  country_code VARCHAR(10) NOT NULL DEFAULT 'jo',
  title TEXT NULL,
  url VARCHAR(1000) NULL,
  status VARCHAR(30) NOT NULL,
  score_before BIGINT NOT NULL DEFAULT 0,
  score_after BIGINT NOT NULL DEFAULT 0,
  decision_id BIGINT UNSIGNED NULL,
  fix_preview_id BIGINT UNSIGNED NULL,
  message TEXT NULL,
  error TEXT NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY idx_content_ai_job_item_order (job_id, item_index),
  INDEX idx_content_ai_job_items_job_id (job_id),
  INDEX idx_content_ai_job_items_status (status),
  INDEX idx_content_ai_job_items_decision_id (decision_id),
  INDEX idx_content_ai_job_items_fix_preview_id (fix_preview_id),
  INDEX idx_content_ai_job_item_content (content_type, content_id),
  CONSTRAINT fk_content_ai_jobs_items FOREIGN KEY (job_id) REFERENCES content_ai_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_ai_model_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id VARCHAR(80) NULL,
  job_item_id BIGINT UNSIGNED NULL,
  content_type VARCHAR(30) NULL,
  content_id VARCHAR(80) NULL,
  country_code VARCHAR(10) NULL,
  task_type VARCHAR(60) NOT NULL,
  model_strategy VARCHAR(40) NULL,
  provider VARCHAR(60) NULL,
  model VARCHAR(180) NOT NULL,
  role VARCHAR(40) NULL,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  estimated_cost_usd DECIMAL(12,6) NOT NULL DEFAULT 0,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  error TEXT NULL,
  created_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  INDEX idx_content_ai_model_runs_job_id (job_id),
  INDEX idx_content_ai_model_runs_job_item_id (job_item_id),
  INDEX idx_content_ai_model_runs_model (model),
  INDEX idx_content_ai_model_runs_status (status),
  INDEX idx_content_ai_model_runs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
